import Head from 'next/head';
import About from '../components/About';
import Main from '../components/Main';
import Projects from '../components/Projects';
import Skills from '../components/Skills';
import Recommendations from '../components/Recommendations/Recommendations';
import Contact from '../components/Contact';
import Footer from '../components/Footer';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Stephen Annor | Full-Stack Developer</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/animate.css@3.5.2/animate.min.css"/>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/Logo.png" />
      </Head>
      <Main />
      <About />
      <Skills />
      <Projects />
      <Recommendations />
      <Contact />
      <Footer />
    </div>
  )
}
